### ISSUE TITLE
PPKPeer's discoveryInfo contains nil value when it shouldn't

### ISSUE THREAD

**Issue by brandonemrich** [Uepaa-AG/p2pkit-quickstart-ios#2]
About 1/3 of the time I run my project on one device while the other device is in the background. The background device doesn't send it's discoveryInfo, but still completes p2p discovery. Fairly certain that this isn't an issue with my implementation since the integration was pretty straight forward. 

Any insight or help is much appreciated!
Brandon

**Comment by thupa** [comment]
Hi Brandon,
Thanks for the information, what you are describing certainly sounds
unusual.

Would it be possible to describe step by step how to reproduce this issue
and perhaps give us a small code example? It would really help!

Thanks!

On 21 Nov 2015, at 01:31, Brandon Emrich <notifications@github.com> wrote:

About 1/3 of the time I run my project on one device while the other device
is in the background. The background device doesn't send it's
discoveryInfo, but still completes p2p discovery. Fairly certain that this
isn't an issue with my implementation since the integration was pretty
straight forward.

Any insight or help is much appreciated!
Brandon

—
Reply to this email directly or view it on GitHub
<https://github.com/Uepaa-AG/p2pkit-quickstart-ios/issues/2>.

**Comment by brandonemrich** [comment]
Kind of tough to provide a code sample for this issue as it's not specific to one piece of code. Maybe some insight into how exactly the PPKPeer's discovery info is saved might help? One device is definitely not sending the discovery info when the connection is made, but like I said that device is in stand by locked and in the background. Could this be a access issue to the discoveryInfo data at connection time by that device, so it sends a nil value?

**Comment by brandonemrich** [comment]
Also it is a swift project on iOS 9 if that helps.

**Comment by thupa** [comment]
Hi Brandon,

May I ask what do you mean "device doesn't send it's discoveryInfo" ? do you get a `func p2pPeerDiscovered(peer: PPKPeer!)` callback and the `PPKPeer.discoveryInfo` value is nil?

On a general note, If you are using discovery info, you should start p2p discovery in the following way:
```swift
PPKController.startP2PDiscoveryWithDiscoveryInfo(myDiscoveryInfo)
```

In case you are accidentally starting P2PDiscovery without the discoveryInfo, and only at a later point call ```PPKController.pushNewP2PDiscoveryInfo(myDiscoveryInfo)``` naturally there is the possibility that first you would discover the peer without the info, and the method ```func didUpdateP2PDiscoveryInfoForPeer(peer: PPKPeer!)``` will follow at a later stage

**Comment by brandonemrich** [comment]
I never start the P2P Discovery without `startP2PDiscoveryWithDiscoveryInfo(myDiscoveryInfo)` and I pass `UIDevice.currentDevice().name.dataUsingEncoding(NSUTF8StringEncoding)` as the DiscoveryInfo. I call `startP2PDiscoveryWithDiscoveryInfo(myDiscoveryInfo)` in the AppDelegate when the PPKControllerDelegate's `PPKControllerInitialized()` is called along with `startGeoDiscovery()` and `startOnlineMessaging()`

I assume these are the correct steps to initiate p2pkit, based on the guide in this repo.

**Comment by thupa** [comment]
Yes, these steps are correct, although there is no need to start GEO and Messaging if you do not need them.

I find the issue you are describing very unexpected but unfortunately it is very hard for us to try and help as long as we stay on a generic level. In order to proceed we would need some code sample so that we can evaluate potential threading issues and such.

On a general note, discovery info goes hand in had with the discovery event so when you get one, you should also get the other, they are both stored in non persistent memory.

If you do not feel comfortable posting code here, you can email us at p2pkit@uepaa.ch

Best!
